sudo: required
os:
  - linux
  - osx
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# versions of java to test (for parsers)
before_install:
  - sudo apt-get update
# command to install dependencies
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - pip install --upgrade pip setuptools wheel
  - pip install pytest coverage pytest-timeout
  - pip install python-coveralls
  - pip install --upgrade coverage
  - pip install .
# command to run tests
script:
  - coverage run --branch -m pytest -v --timeout=90 && coverage report -m
after_success:
  - coveralls
