language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - python --version
  - pip install --upgrade pip setuptools wheel
  - pip install pytest coverage pytest-timeout
  - pip install coveralls
  - pip install --upgrade coverage
  - pip install .
script:
  - coverage run --branch -m pytest -v --timeout=90 && coverage report -m
after_success:
  - coveralls
